name: Code Style

on:
  push:
    branches: [ main, master, '**' ]
  pull_request:
    branches: [ main, master, '**' ]

jobs:
  php-cs-fixer:
    name: PHP CS Fixer (PSR-12)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Code style check (php-cs-fixer dry-run)
        run: |
          vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no

